pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ThisIs-Developer/Wipro-SDET'
            }
        }

        stage('Build') {
            steps {
                dir('ProjectPHPTravels') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('ProjectPHPTravels') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ProjectPHPTravels') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('ProjectPHPTravels') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}